### ISSUE TITLE
Нет возможности сохранять расписание на устройство

### ISSUE THREAD

**Issue by boumer7** [Nikololoshka/ProjectPepega#3]
Нет возможности сохранять расписания на устройство, хотя все разрешения приложению даны
![image](https://github.com/Nikololoshka/ProjectPepega/assets/33152397/81c80790-73b0-42ce-9c4b-f0c6d0dba533)

**Comment by Nikololoshka** [comment]
Доброго времени суток! 

Раз приложению разрешение дано, то могу предположить, что, возможно, есть проблема в логике получении "write permission" для более поздних версий android (где оно уже не нужно).

Не подскажите какая у вас версия Android?

**Comment by boumer7** [comment]
Добрый вечер, благодарю за ответ

Версия Android 10 QP1A.190711.020

**Comment by boumer7** [comment]
Само приложение очень добротно сделано

**Comment by Nikololoshka** [comment]
Доброго времени суток!

Смотрел на эмуляторе Android 10, раньше действильно не работало сохранение. Исправил это в версии 2.1.1. Через Google Play, правда, обновление придет не сразу. Нужно будет подождать.

**Comment by boumer7** [comment]
Благодарю

**Comment by boumer7** [comment]
Возможность сохранения протестирована и всё отлично работает.
Благодарю разработчика за оперативное исправление и связь
